site: zackenberg
aoi: shp/zackenberg_aoi.gpkg
target_epsg: 32627

# Raw HDF download destination
hdf_dir: /mnt/glaciologi/GEM/remote_sensing_and_modelling/data/MODIS_CGF_SCF/zackenberg/

# MODIS product and time range
modis_product: MOD10A1F
temporal_start: "2000-02-24"
temporal_end: "2025-12-31"

# Masking shapefiles
land_shp: /home/shl/mdrev/data/sdfi/G250_VEKTOR/Land.shp
ice_shp: /home/shl/mdrev/data/sdfi/G250_VEKTOR/Is.shp

# In situ validation
station_id: zackenberg
aws_stations: data/CARRA/AWS_station_locations.csv
