site: zackenberg
aoi: shp/zackenberg_aoi.gpkg
target_epsg: 32627

# Raw HDF download destination
hdf_dir: /mnt/glaciologi/GEM/remote_sensing_and_modelling/data/MODIS_CGF_SCF/zackenberg/

# MODIS product and time range
modis_product: MOD10A1F
temporal_start: "2000-02-24"
temporal_end: "2025-12-31"

# Masking shapefiles
land_shp: /home/shl/mdrev/data/sdfi/G250_VEKTOR/Land.shp
ice_shp: /home/shl/mdrev/data/sdfi/G250_VEKTOR/Is.shp

# In situ validation
station_id: zackenberg
aws_stations: data/mast_locations.csv
gem_dir: /home/shl/mdrev/data/GEM/zackenberg/
insitu_temperature: Air_temperature_200cm_60_30min_sample_10.17897_G5WS-0W04_data.txt
insitu_snowdepth: Snow depth - 180min sample (m)_10.17897_7RVV-Z412_data.txt
insitu_swin: "Short wave incoming radiation  200 cm - 5min average (W_m2)_10.17897_5T0P-N482_data.txt"
insitu_swout: "Short wave outgoing radiation  200 cm - 5min average (W_m2)_10.17897_NF8K-FC03_data.txt"